import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { KnowledgeBaseConfig } from "../src/knowledge.js";

// --- Mocks ---

const execJsonMock = vi.fn();

vi.mock("../src/utils/exec.js", () => ({
  exec: vi.fn().mockResolvedValue({ stdout: "", stderr: "" }),
  execJson: (...args: unknown[]) => execJsonMock(...args),
}));

vi.mock("../src/utils/logger.js", () => ({
  logger: {
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
    debug: vi.fn(),
  },
}));

vi.mock("../src/knowledge.js", () => ({
  isHighSignalCandidate: vi.fn().mockReturnValue({ accepted: true }),
  saveKnowledgeBase: vi
    .fn()
    .mockResolvedValue({ ok: true, status: "saved", entryId: "test-id" }),
  getKnowledgeBaseConfig: vi.fn().mockReturnValue({
    enabled: true,
    qdrantUrl: "https://test.example.com",
    qdrantApiKey: "key",
    writeEnabled: true,
    defaultMaxResults: 6,
    embeddingModel: "text-embedding-3-small",
    dedupThreshold: 0.92,
  }),
  checkKnowledgeBaseHealth: vi
    .fn()
    .mockResolvedValue({ ok: true, collectionReady: true, writable: true }),
}));

vi.mock("../src/model.js", () => ({
  parseModelString: vi.fn().mockReturnValue({
    provider: "anthropic",
    modelId: "claude-sonnet-4-5-20250929",
  }),
  getApiKey: vi.fn().mockReturnValue("test-api-key"),
}));

const mockGetModel = vi.fn().mockReturnValue({
  id: "claude-sonnet-4-5-20250929",
  name: "claude-sonnet-4-5-20250929",
  api: "anthropic-messages-stream",
  provider: "anthropic",
  baseUrl: "https://api.anthropic.com",
  reasoning: false,
  input: ["text"],
  cost: { input: 0.003, output: 0.015, cacheRead: 0, cacheWrite: 0 },
  contextWindow: 200000,
  maxTokens: 8192,
});

vi.mock("@mariozechner/pi-ai", () => ({
  getModel: (...args: unknown[]) => mockGetModel(...args),
}));

let mockSessionResponse = "[]";
let mockSessionError: string | undefined;
let mockSessionMessages: unknown[] = [];

vi.mock("@mariozechner/pi-coding-agent", () => ({
  createAgentSession: vi.fn().mockImplementation(async () => ({
    session: {
      prompt: vi.fn().mockResolvedValue(undefined),
      getLastAssistantText: () => mockSessionResponse,
      state: { error: mockSessionError, messages: mockSessionMessages },
      subscribe: vi.fn(),
    },
  })),
  SessionManager: { inMemory: vi.fn().mockReturnValue({}) },
  SettingsManager: { inMemory: vi.fn().mockReturnValue({}) },
  DefaultResourceLoader: vi.fn().mockImplementation(() => ({
    reload: vi.fn().mockResolvedValue(undefined),
  })),
}));

import { isHighSignalCandidate, saveKnowledgeBase } from "../src/knowledge.js";

const SAMPLE_CONFIG: KnowledgeBaseConfig = {
  enabled: true,
  qdrantUrl: "https://test-qdrant.example.com",
  qdrantApiKey: "test-key",
  writeEnabled: true,
  defaultMaxResults: 6,
  embeddingModel: "text-embedding-3-small",
  dedupThreshold: 0.92,
};

const HODOR_REVIEW_BODY = `### Issues Found

**Critical (P0/P1)**
- **Null pointer risk in parseConfig** ([src/config.ts:42-48](link))
  - The destructured options object is not null-checked.

### Overall Verdict
**Status**: Patch has blocking issues

---

Review generated by Hodor (model: \`anthropic/claude-sonnet-4-5-20250929\`)`;

beforeEach(() => {
  vi.clearAllMocks();
  execJsonMock.mockReset();
  mockSessionResponse = "[]";
  mockSessionError = undefined;
  mockSessionMessages = [];
});

afterEach(() => {
  delete process.env.HODOR_KB_EXTRACT_MODEL;
});

describe("fetchFeedbackContext — GitHub", () => {
  it("finds Hodor review in review submissions and collects feedback", async () => {
    const { fetchFeedbackContext } = await import("../src/feedback.js");

    execJsonMock.mockImplementation(async (_cmd: string, args: string[]) => {
      const endpoint = args[1];
      if (endpoint.includes("/issues/")) {
        return [
          {
            id: 201,
            body: "Thanks for the review! The null check isn't needed because options is always validated upstream in loadConfig().",
            user: { login: "dev-alice" },
            created_at: "2026-03-18T12:00:00Z",
          },
        ];
      }
      if (endpoint.includes("/reviews")) {
        return [
          {
            id: 100,
            body: HODOR_REVIEW_BODY,
            state: "COMMENTED",
            user: { login: "hodor-bot" },
            submitted_at: "2026-03-18T11:00:00Z",
          },
        ];
      }
      return [];
    });

    const ctx = await fetchFeedbackContext(
      "https://github.com/acme/api/pull/42",
    );

    expect(ctx).not.toBeNull();
    expect(ctx!.hodorReview.body).toContain("Review generated by Hodor");
    expect(ctx!.hodorReview.platform).toBe("github");
    expect(ctx!.feedbackComments).toHaveLength(1);
    expect(ctx!.feedbackComments[0].author).toBe("dev-alice");
    expect(ctx!.feedbackComments[0].body).toContain("validated upstream");
    expect(ctx!.preReviewComments).toHaveLength(0);
  });

  it("returns null when no Hodor review is found", async () => {
    const { fetchFeedbackContext } = await import("../src/feedback.js");

    execJsonMock.mockResolvedValue([]);

    const ctx = await fetchFeedbackContext(
      "https://github.com/acme/api/pull/42",
    );
    expect(ctx).toBeNull();
  });

  it("separates pre-review and post-review comments", async () => {
    const { fetchFeedbackContext } = await import("../src/feedback.js");

    execJsonMock.mockImplementation(async (_cmd: string, args: string[]) => {
      const endpoint = args[1];
      if (endpoint.includes("/issues/")) {
        return [
          {
            id: 200,
            body: "Pre-review discussion about the approach",
            user: { login: "dev-bob" },
            created_at: "2026-03-18T10:00:00Z",
          },
          {
            id: 201,
            body: "Post-review feedback that should be included",
            user: { login: "dev-alice" },
            created_at: "2026-03-18T12:00:00Z",
          },
        ];
      }
      if (endpoint.includes("/reviews")) {
        return [
          {
            id: 100,
            body: HODOR_REVIEW_BODY,
            state: "COMMENTED",
            user: { login: "hodor-bot" },
            submitted_at: "2026-03-18T11:00:00Z",
          },
        ];
      }
      return [];
    });

    const ctx = await fetchFeedbackContext(
      "https://github.com/acme/api/pull/42",
    );

    expect(ctx).not.toBeNull();
    expect(ctx!.feedbackComments).toHaveLength(1);
    expect(ctx!.feedbackComments[0].body).toContain("Post-review feedback");
    expect(ctx!.preReviewComments).toHaveLength(1);
    expect(ctx!.preReviewComments[0].body).toContain("Pre-review discussion");
    expect(ctx!.preReviewComments[0].author).toBe("dev-bob");
  });

  it("excludes other Hodor reviews from feedback", async () => {
    const { fetchFeedbackContext } = await import("../src/feedback.js");

    execJsonMock.mockImplementation(async (_cmd: string, args: string[]) => {
      const endpoint = args[1];
      if (endpoint.includes("/issues/")) {
        return [];
      }
      if (endpoint.includes("/reviews")) {
        return [
          {
            id: 100,
            body: HODOR_REVIEW_BODY,
            state: "COMMENTED",
            user: { login: "hodor-bot" },
            submitted_at: "2026-03-18T11:00:00Z",
          },
          {
            id: 101,
            body: "Second review\n\n---\n\nReview generated by Hodor (model: `test`)",
            state: "COMMENTED",
            user: { login: "hodor-bot" },
            submitted_at: "2026-03-18T13:00:00Z",
          },
        ];
      }
      return [];
    });

    const ctx = await fetchFeedbackContext(
      "https://github.com/acme/api/pull/42",
    );

    expect(ctx).not.toBeNull();
    expect(ctx!.feedbackComments).toHaveLength(0);
  });
});

describe("fetchFeedbackContext — GitLab", () => {
  it("finds Hodor review in GitLab MR notes and collects feedback", async () => {
    const { fetchFeedbackContext } = await import("../src/feedback.js");

    execJsonMock.mockImplementation(async (_cmd: string, args: string[]) => {
      const endpoint = args[1] as string;
      if (endpoint.includes("/notes")) {
        return [
          {
            body: HODOR_REVIEW_BODY,
            author: { username: "hodor-bot" },
            created_at: "2026-03-18T11:00:00Z",
            system: false,
          },
          {
            body: "The null check is handled upstream by loadConfig(). This always validates before parseConfig runs.",
            author: { username: "dev-alice" },
            created_at: "2026-03-18T12:00:00Z",
            system: false,
          },
        ];
      }
      return { title: "Test MR", description: "MR description" };
    });

    const ctx = await fetchFeedbackContext(
      "https://gitlab.com/acme/api/-/merge_requests/42",
    );

    expect(ctx).not.toBeNull();
    expect(ctx!.hodorReview.platform).toBe("gitlab");
    expect(ctx!.feedbackComments).toHaveLength(1);
    expect(ctx!.feedbackComments[0].author).toBe("dev-alice");
  });

  it("separates pre-review and post-review notes on GitLab", async () => {
    const { fetchFeedbackContext } = await import("../src/feedback.js");

    execJsonMock.mockImplementation(async (_cmd: string, args: string[]) => {
      const endpoint = args[1] as string;
      if (endpoint.includes("/notes")) {
        return [
          {
            body: "Initial discussion before review",
            author: { username: "dev-bob" },
            created_at: "2026-03-18T09:00:00Z",
            system: false,
          },
          {
            body: HODOR_REVIEW_BODY,
            author: { username: "hodor-bot" },
            created_at: "2026-03-18T11:00:00Z",
            system: false,
          },
          {
            body: "Correction: loadConfig always runs validation before parseConfig.",
            author: { username: "dev-alice" },
            created_at: "2026-03-18T12:00:00Z",
            system: false,
          },
        ];
      }
      return { title: "Test MR" };
    });

    const ctx = await fetchFeedbackContext(
      "https://gitlab.com/acme/api/-/merge_requests/42",
    );

    expect(ctx).not.toBeNull();
    expect(ctx!.feedbackComments).toHaveLength(1);
    expect(ctx!.feedbackComments[0].body).toContain("Correction");
    expect(ctx!.preReviewComments).toHaveLength(1);
    expect(ctx!.preReviewComments[0].body).toContain("Initial discussion");
  });

  it("ignores system notes on GitLab", async () => {
    const { fetchFeedbackContext } = await import("../src/feedback.js");

    execJsonMock.mockImplementation(async (_cmd: string, args: string[]) => {
      const endpoint = args[1] as string;
      if (endpoint.includes("/notes")) {
        return [
          {
            body: HODOR_REVIEW_BODY,
            author: { username: "hodor-bot" },
            created_at: "2026-03-18T11:00:00Z",
            system: false,
          },
          {
            body: "approved this merge request",
            author: { username: "dev-bob" },
            created_at: "2026-03-18T12:00:00Z",
            system: true,
          },
        ];
      }
      return { title: "Test MR" };
    });

    const ctx = await fetchFeedbackContext(
      "https://gitlab.com/acme/api/-/merge_requests/42",
    );

    expect(ctx).not.toBeNull();
    expect(ctx!.feedbackComments).toHaveLength(0);
  });
});

describe("runFeedbackExtraction", () => {
  const SAMPLE_FEEDBACK_CONTEXT = {
    hodorReview: {
      body: HODOR_REVIEW_BODY,
      created_at: "2026-03-18T11:00:00Z",
      platform: "github" as const,
    },
    feedbackComments: [
      {
        body: "The null check isn't needed because options always goes through loadConfig() first which validates all fields before parseConfig is called.",
        author: "dev-alice",
        created_at: "2026-03-18T12:00:00Z",
      },
    ],
    preReviewComments: [] as Array<{
      body: string;
      author: string;
      created_at: string;
    }>,
  };

  const SAMPLE_FEEDBACK_EXTRACTION_RESPONSE = JSON.stringify([
    {
      learning:
        "The loadConfig() function always validates and normalizes all option fields before parseConfig() uses them downstream.",
      category: "coding_pattern",
      evidence:
        "Developer confirmed that options go through loadConfig() validation before parseConfig is called, making null checks redundant.",
      stability: "high",
      scope_tags: ["config", "validation"],
      paths: ["src/config.ts"],
      symbols: ["loadConfig", "parseConfig"],
      source_pr: "https://github.com/acme/api/pull/42",
    },
  ]);

  it("extracts and saves learnings from feedback (model resolved internally)", async () => {
    const { runFeedbackExtraction } = await import("../src/feedback.js");

    mockSessionResponse = SAMPLE_FEEDBACK_EXTRACTION_RESPONSE;
    mockSessionMessages = [
      {
        role: "assistant",
        usage: {
          input: 200,
          output: 80,
          cacheRead: 0,
          cacheWrite: 0,
          totalTokens: 280,
          cost: { total: 0.0045 },
        },
      },
    ];

    const result = await runFeedbackExtraction({
      config: SAMPLE_CONFIG,
      targetRepo: "acme/api",
      prUrl: "https://github.com/acme/api/pull/42",
      model: "anthropic/claude-sonnet-4-5-20250929",
      feedbackContext: SAMPLE_FEEDBACK_CONTEXT,
    });

    expect(result.extracted).toBe(1);
    expect(result.saved).toBe(1);
    expect(result.llmMetrics?.totalTokens).toBe(280);
    expect(saveKnowledgeBase).toHaveBeenCalledOnce();
    expect(mockGetModel).toHaveBeenCalled();
  });

  it("returns empty when no feedback comments exist", async () => {
    const { runFeedbackExtraction } = await import("../src/feedback.js");

    const result = await runFeedbackExtraction({
      config: SAMPLE_CONFIG,
      targetRepo: "acme/api",
      prUrl: "https://github.com/acme/api/pull/42",
      model: "anthropic/claude-sonnet-4-5-20250929",
      feedbackContext: {
        ...SAMPLE_FEEDBACK_CONTEXT,
        feedbackComments: [],
      },
    });

    expect(result.extracted).toBe(0);
    expect(result.saved).toBe(0);
  });

  it("respects dry-run mode — does not call saveKnowledgeBase", async () => {
    const { runFeedbackExtraction } = await import("../src/feedback.js");

    mockSessionResponse = SAMPLE_FEEDBACK_EXTRACTION_RESPONSE;

    const result = await runFeedbackExtraction({
      config: SAMPLE_CONFIG,
      targetRepo: "acme/api",
      prUrl: "https://github.com/acme/api/pull/42",
      model: "anthropic/claude-sonnet-4-5-20250929",
      feedbackContext: SAMPLE_FEEDBACK_CONTEXT,
      dryRun: true,
    });

    expect(result.extracted).toBe(1);
    expect(result.saved).toBe(1);
    expect(saveKnowledgeBase).not.toHaveBeenCalled();
  });

  it("rejects candidates that fail high-signal validation", async () => {
    const { runFeedbackExtraction } = await import("../src/feedback.js");

    mockSessionResponse = SAMPLE_FEEDBACK_EXTRACTION_RESPONSE;
    vi.mocked(isHighSignalCandidate).mockReturnValueOnce({
      accepted: false,
      reason: "learning appears incidental",
    });

    const result = await runFeedbackExtraction({
      config: SAMPLE_CONFIG,
      targetRepo: "acme/api",
      prUrl: "https://github.com/acme/api/pull/42",
      model: "anthropic/claude-sonnet-4-5-20250929",
      feedbackContext: SAMPLE_FEEDBACK_CONTEXT,
    });

    expect(result.extracted).toBe(1);
    expect(result.rejected).toBe(1);
    expect(result.saved).toBe(0);
  });

  it("handles LLM errors gracefully", async () => {
    const { runFeedbackExtraction } = await import("../src/feedback.js");

    mockSessionError = "model overloaded";

    const result = await runFeedbackExtraction({
      config: SAMPLE_CONFIG,
      targetRepo: "acme/api",
      prUrl: "https://github.com/acme/api/pull/42",
      model: "anthropic/claude-sonnet-4-5-20250929",
      feedbackContext: SAMPLE_FEEDBACK_CONTEXT,
    });

    expect(result.extracted).toBe(0);
    expect(result.errors.length).toBeGreaterThan(0);
    expect(result.errors[0]).toContain("model overloaded");
  });

  it("handles empty extraction response", async () => {
    const { runFeedbackExtraction } = await import("../src/feedback.js");

    mockSessionResponse = "[]";

    const result = await runFeedbackExtraction({
      config: SAMPLE_CONFIG,
      targetRepo: "acme/api",
      prUrl: "https://github.com/acme/api/pull/42",
      model: "anthropic/claude-sonnet-4-5-20250929",
      feedbackContext: SAMPLE_FEEDBACK_CONTEXT,
    });

    expect(result.extracted).toBe(0);
    expect(result.saved).toBe(0);
    expect(result.errors).toHaveLength(0);
  });

  it("strips markdown fences from LLM response", async () => {
    const { runFeedbackExtraction } = await import("../src/feedback.js");

    mockSessionResponse =
      "```json\n" + SAMPLE_FEEDBACK_EXTRACTION_RESPONSE + "\n```";

    const result = await runFeedbackExtraction({
      config: SAMPLE_CONFIG,
      targetRepo: "acme/api",
      prUrl: "https://github.com/acme/api/pull/42",
      model: "anthropic/claude-sonnet-4-5-20250929",
      feedbackContext: SAMPLE_FEEDBACK_CONTEXT,
    });

    expect(result.extracted).toBe(1);
    expect(result.saved).toBe(1);
  });

  it("returns empty when config is disabled (non-dry-run)", async () => {
    const { runFeedbackExtraction } = await import("../src/feedback.js");

    const result = await runFeedbackExtraction({
      config: { ...SAMPLE_CONFIG, enabled: false },
      targetRepo: "acme/api",
      prUrl: "https://github.com/acme/api/pull/42",
      model: "anthropic/claude-sonnet-4-5-20250929",
      feedbackContext: SAMPLE_FEEDBACK_CONTEXT,
    });

    expect(result.extracted).toBe(0);
    expect(result.saved).toBe(0);
  });

  it("includes pre-review comments as context in the prompt", async () => {
    const { runFeedbackExtraction } = await import("../src/feedback.js");
    const { createAgentSession } =
      await import("@mariozechner/pi-coding-agent");

    mockSessionResponse = "[]";

    await runFeedbackExtraction({
      config: SAMPLE_CONFIG,
      targetRepo: "acme/api",
      prUrl: "https://github.com/acme/api/pull/42",
      model: "anthropic/claude-sonnet-4-5-20250929",
      feedbackContext: {
        ...SAMPLE_FEEDBACK_CONTEXT,
        preReviewComments: [
          {
            body: "We discussed the validation approach in the design review and agreed loadConfig() always runs first.",
            author: "dev-bob",
            created_at: "2026-03-18T09:00:00Z",
          },
        ],
      },
    });

    // Verify the prompt was called (session.prompt) — the pre-review context
    // is included in the template and sent to the LLM
    expect(createAgentSession).toHaveBeenCalled();
  });
});

describe("parseFeedbackResponse", () => {
  it("parses valid JSON array", async () => {
    const { parseFeedbackResponse } = await import("../src/feedback.js");

    const result = parseFeedbackResponse(
      JSON.stringify([
        {
          learning:
            "loadConfig always validates before parseConfig runs downstream in the pipeline.",
          category: "coding_pattern",
          evidence: "Developer confirmed the call chain order.",
          stability: "high",
          scope_tags: ["config"],
        },
      ]),
    );

    expect(result).toHaveLength(1);
    expect(result[0].learning).toContain("loadConfig");
    expect(result[0].category).toBe("coding_pattern");
  });

  it("strips markdown fences", async () => {
    const { parseFeedbackResponse } = await import("../src/feedback.js");

    const result = parseFeedbackResponse(
      '```json\n[{"learning":"test fact about the codebase architecture","category":"architecture","evidence":"found in code review","stability":"medium","scope_tags":["test"]}]\n```',
    );

    expect(result).toHaveLength(1);
  });

  it("throws on non-array response", async () => {
    const { parseFeedbackResponse } = await import("../src/feedback.js");

    expect(() => parseFeedbackResponse('{"not": "an array"}')).toThrow(
      "not a JSON array",
    );
  });

  it("returns empty array for empty JSON array", async () => {
    const { parseFeedbackResponse } = await import("../src/feedback.js");

    const result = parseFeedbackResponse("[]");
    expect(result).toHaveLength(0);
  });
});

describe("fetchGithubIssueComments", () => {
  it("fetches and normalizes issue comments", async () => {
    const { fetchGithubIssueComments } = await import("../src/github.js");

    execJsonMock.mockResolvedValueOnce([
      {
        id: 1,
        body: "Looks good to me",
        user: { login: "reviewer1", name: "Reviewer One" },
        created_at: "2026-03-18T10:00:00Z",
      },
      {
        id: 2,
        body: "Please fix the null check",
        user: { login: "reviewer2" },
        created_at: "2026-03-18T11:00:00Z",
      },
    ]);

    const comments = await fetchGithubIssueComments("acme", "api", 42);

    expect(comments).toHaveLength(2);
    expect(comments[0].id).toBe(1);
    expect(comments[0].body).toBe("Looks good to me");
    expect(comments[0].author.username).toBe("reviewer1");
    expect(comments[1].author.username).toBe("reviewer2");
  });
});

describe("fetchGithubReviewComments", () => {
  it("fetches and normalizes review submissions", async () => {
    const { fetchGithubReviewComments } = await import("../src/github.js");

    execJsonMock.mockResolvedValueOnce([
      {
        id: 10,
        body: "LGTM",
        state: "APPROVED",
        user: { login: "lead-reviewer" },
        submitted_at: "2026-03-18T12:00:00Z",
      },
    ]);

    const reviews = await fetchGithubReviewComments("acme", "api", 42);

    expect(reviews).toHaveLength(1);
    expect(reviews[0].state).toBe("APPROVED");
    expect(reviews[0].author.username).toBe("lead-reviewer");
  });
});
