import pytest

from hodor.agent import _format_metrics_markdown, detect_platform, parse_pr_url, post_review_comment


@pytest.mark.parametrize(
    "url,expected",
    [
        ("https://github.com/foo/bar/pull/42", "github"),
        ("https://gitlab.com/foo/bar/-/merge_requests/3", "gitlab"),
        ("https://gitlab.example.dev/group/repo/-/merge_requests/19", "gitlab"),
    ],
)
def test_detect_platform(url, expected):
    assert detect_platform(url) == expected


def test_parse_pr_url_github():
    owner, repo, number, host = parse_pr_url("https://github.com/octo/hoDor/pull/123")
    assert owner == "octo"
    assert repo == "hoDor"
    assert number == 123
    assert host == "github.com"


def test_parse_pr_url_gitlab_subgroups():
    url = "https://gitlab.example.com/org/security/tools/hodor/-/merge_requests/99"
    owner, repo, number, host = parse_pr_url(url)
    assert owner == "org/security/tools"
    assert repo == "hodor"
    assert number == 99
    assert host == "gitlab.example.com"


def test_parse_pr_url_invalid():
    with pytest.raises(ValueError):
        parse_pr_url("https://gitlab.com/foo/bar/issues/1")


def test_format_metrics_markdown_includes_expected_fields():
    markdown = _format_metrics_markdown(
        {
            "prompt_tokens": 1000,
            "completion_tokens": 80,
            "cache_read_tokens": 900,
            "cache_write_tokens": 0,
            "reasoning_tokens": 20,
            "fresh_input_tokens": 100,
            "total_tokens": 1100,
            "cache_hit_rate": 90.0,
            "cost": 1.2345,
            "review_time_seconds": 125,
            "review_time_str": "2m 5s",
        }
    )

    assert "**Review Metrics**" in markdown
    assert "- Tokens: in `1.0K` (cache `900` | fresh `100`) | out `80` | total `1.1K`" in markdown
    assert "Cost: `$1.2345`" in markdown
    assert "Duration: `2m 5s`" in markdown


def test_post_review_comment_appends_model_and_metrics_footer(monkeypatch):
    captured: dict[str, str] = {}

    def _fake_run(args, check, capture_output, text):
        body_index = args.index("--body") + 1
        captured["body"] = args[body_index]

    monkeypatch.setattr("subprocess.run", _fake_run)

    result = post_review_comment(
        pr_url="https://github.com/foo/bar/pull/42",
        review_text="Review body",
        model="openai/gpt-5",
        metrics_footer="**Review Metrics**\n- Total: `123`",
    )

    assert result["success"] is True
    assert "Review generated by Hodor (model: `openai/gpt-5`)" in captured["body"]
    assert "**Review Metrics**" in captured["body"]
