import { existsSync } from "node:fs";
import { join } from "node:path";
import type { ToolDefinition } from "@mariozechner/pi-coding-agent";
import { logger } from "./utils/logger.js";
import { exec } from "./utils/exec.js";
import { fetchGithubPrInfo, normalizeGithubMetadata } from "./github.js";
import { fetchGitlabMrInfo, postGitlabMrComment } from "./gitlab.js";
import { setupWorkspace, cleanupWorkspace } from "./workspace.js";
import { buildPrReviewPrompt } from "./prompt.js";
import { parseModelString, mapReasoningEffort, getApiKey } from "./model.js";
import { formatMetricsMarkdown, printMetrics } from "./metrics.js";
import { SUBMIT_REVIEW_SCHEMA, validateReviewOutput } from "./review.js";
import { REVIEW_SYSTEM_PROMPT } from "./system-prompt.js";
import {
  QUERY_KNOWLEDGE_BASE_SCHEMA,
  SAVE_KNOWLEDGE_BASE_SCHEMA,
  checkKnowledgeBaseHealth,
  getKnowledgeBaseConfig,
  queryKnowledgeBase,
  saveKnowledgeBase,
} from "./knowledge.js";
import type {
  Platform,
  ParsedPrUrl,
  ReviewMetrics,
  PostCommentResult,
  MrMetadata,
  RenderContext,
  ReviewOutput,
} from "./types.js";

export interface AgentProgressEvent {
  type:
    | "tool_start"
    | "tool_end"
    | "thinking"
    | "turn_start"
    | "turn_end"
    | "agent_start"
    | "agent_end"
    | "text_delta"
    | "thinking_delta"
    | "tool_result";
  toolName?: string;
  toolArgs?: string;
  isError?: boolean;
  turnIndex?: number;
  delta?: string;
  result?: string;
}

export function detectPlatform(prUrl: string): Platform {
  const url = new URL(prUrl);
  const hostname = url.hostname;
  if (prUrl.includes("/-/merge_requests/") || hostname.includes("gitlab")) {
    return "gitlab";
  }
  if (prUrl.includes("/pull/") || hostname.includes("github")) {
    return "github";
  }
  throw new Error(
    `Cannot detect platform for URL: ${prUrl}. Expected a GitHub pull request (/pull/) or GitLab merge request (/-/merge_requests/) URL.`,
  );
}

export function parsePrUrl(prUrl: string): ParsedPrUrl {
  const url = new URL(prUrl);
  const pathParts = url.pathname.split("/").filter(Boolean);
  const host = url.host;

  // GitHub format: /owner/repo/pull/123
  if (pathParts.length >= 4 && pathParts[2] === "pull") {
    const prNumber = parseInt(pathParts[3], 10);
    if (!Number.isSafeInteger(prNumber) || prNumber <= 0) {
      throw new Error(
        `Invalid PR number in URL: ${prUrl}. Expected a positive integer after /pull/.`,
      );
    }
    return {
      owner: pathParts[0],
      repo: pathParts[1],
      prNumber,
      host,
    };
  }

  // GitLab format: /group/subgroup/repo/-/merge_requests/123
  const mrIndex = pathParts.indexOf("merge_requests");
  if (mrIndex >= 0) {
    if (mrIndex < 2 || mrIndex + 1 >= pathParts.length) {
      throw new Error(
        `Invalid GitLab MR URL format: ${prUrl}. Expected .../-/merge_requests/<number>`,
      );
    }
    if (pathParts[mrIndex - 1] !== "-") {
      throw new Error(
        `Invalid GitLab MR URL format: ${prUrl}. Missing '/-/' segment before merge_requests.`,
      );
    }

    const repo = pathParts[mrIndex - 2];
    const ownerParts = pathParts.slice(0, mrIndex - 2);
    const owner = ownerParts.length > 0 ? ownerParts.join("/") : pathParts[0];
    const prNumber = parseInt(pathParts[mrIndex + 1], 10);
    if (!Number.isSafeInteger(prNumber) || prNumber <= 0) {
      throw new Error(
        `Invalid MR number in URL: ${prUrl}. Expected a positive integer after /merge_requests/.`,
      );
    }
    return { owner, repo, prNumber, host };
  }

  throw new Error(
    `Invalid PR/MR URL format: ${prUrl}. Expected GitHub pull request or GitLab merge request URL.`,
  );
}

export async function postReviewComment(opts: {
  prUrl: string;
  reviewText: string;
  model?: string | null;
  metricsFooter?: string | null;
}): Promise<PostCommentResult> {
  const { prUrl, reviewText, model, metricsFooter } = opts;
  const platform = detectPlatform(prUrl);
  logger.info(`Posting comment to ${platform} PR/MR: ${prUrl}`);

  let parsed: ParsedPrUrl;
  try {
    parsed = parsePrUrl(prUrl);
  } catch (err) {
    return { success: false, error: String(err) };
  }

  let body = reviewText;
  if (model) {
    body = `${body}\n\n---\n\nReview generated by Hodor (model: \`${model}\`)`;
  }
  if (metricsFooter) {
    body = `${body}\n\n${metricsFooter}`;
  }

  try {
    if (platform === "github") {
      await exec("gh", [
        "pr",
        "review",
        String(parsed.prNumber),
        "--repo",
        `${parsed.owner}/${parsed.repo}`,
        "--comment",
        "--body",
        body,
      ]);
      logger.info(
        `Successfully posted review to GitHub PR #${parsed.prNumber}`,
      );
      return { success: true, platform: "github", prNumber: parsed.prNumber };
    } else {
      await postGitlabMrComment(
        parsed.owner,
        parsed.repo,
        parsed.prNumber,
        body,
        parsed.host,
      );
      logger.info(
        `Successfully posted review to GitLab MR !${parsed.prNumber}`,
      );
      return {
        success: true,
        platform: "gitlab",
        mrNumber: parsed.prNumber,
      };
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.error(`Failed to post comment: ${msg}`);
    return { success: false, error: msg };
  }
}

export async function reviewPr(opts: {
  prUrl: string;
  model?: string;
  reasoningEffort?: string;
  customPrompt?: string | null;
  promptFile?: string | null;
  cleanup?: boolean;
  workspaceDir?: string | null;
  includeMetricsFooter?: boolean;
  onEvent?: (event: AgentProgressEvent) => void;
}): Promise<{ review: ReviewOutput; metricsFooter: string | null; renderContext: RenderContext }> {
  const {
    prUrl,
    model = "anthropic/claude-sonnet-4-5-20250929",
    reasoningEffort,
    customPrompt,
    promptFile,
    cleanup = true,
    workspaceDir,
    includeMetricsFooter = false,
    onEvent,
  } = opts;

  logger.info(`Starting PR review for: ${prUrl}`);

  // Parse PR URL
  const { owner, repo, prNumber, host } = parsePrUrl(prUrl);
  const platform = detectPlatform(prUrl);
  logger.info(
    `Platform: ${platform}, Repo: ${owner}/${repo}, PR: ${prNumber}, Host: ${host}`,
  );

  // --- Preflight: validate model + credentials before any expensive I/O ---
  const parsed = parseModelString(model);
  const thinkingLevel = mapReasoningEffort(reasoningEffort);

  // Resolve API key (throws if missing for non-bedrock providers)
  const apiKey = getApiKey(model);

  // Note: For bedrock, we don't preflight-check AWS credentials because the
  // SDK resolves them from many sources (env vars, IMDS, ECS task role, IRSA,
  // ~/.aws/credentials, etc.) and we can't reliably detect all of them.
  // If credentials are missing, the SDK will fail with a clear error.

  // Snapshot env vars we may mutate, restore in finally block
  const envSnapshot: Record<string, string | undefined> = {
    ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    AWS_REGION: process.env.AWS_REGION,
  };

  // Set API key in environment for pi-ai early so session creation can use it
  if (apiKey) {
    if (parsed.provider === "anthropic") {
      process.env.ANTHROPIC_API_KEY = apiKey;
    } else if (parsed.provider === "openai") {
      process.env.OPENAI_API_KEY = apiKey;
    }
  }

  // Import pi SDK
  const {
    createAgentSession,
    DefaultResourceLoader,
    SessionManager,
    SettingsManager,
    createReadTool,
    createBashTool,
    createGrepTool,
    createFindTool,
    createLsTool,
  } = await import("@mariozechner/pi-coding-agent");
  const { getModel } = await import("@mariozechner/pi-ai");

  // Resolve model — use registry for known models, construct manually for custom ARNs
  let piModel: ReturnType<typeof getModel>;
  if (parsed.modelId.startsWith("arn:")) {
    // Custom bedrock ARN (inference profile, cross-region, etc.)
    // Extract region from ARN: arn:aws:bedrock:<region>:<account>:...
    const arnParts = parsed.modelId.split(":");
    const region = arnParts.length >= 4 ? arnParts[3] : "us-east-1";
    // Set AWS_REGION so the BedrockRuntimeClient uses the correct endpoint
    if (!process.env.AWS_REGION && !process.env.AWS_DEFAULT_REGION) {
      process.env.AWS_REGION = region;
    }
    piModel = {
      id: parsed.modelId,
      name: parsed.modelId,
      api: "bedrock-converse-stream",
      provider: "amazon-bedrock",
      baseUrl: `https://bedrock-runtime.${region}.amazonaws.com`,
      reasoning: false,
      input: ["text"] as ("text" | "image")[],
      cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
      contextWindow: 200000,
      maxTokens: 16384,
    } as ReturnType<typeof getModel>;
    logger.info(`Custom bedrock ARN model — region: ${region}`);
  } else {
    try {
      piModel = getModel(
        parsed.provider as "anthropic",
        parsed.modelId as never,
      );
    } catch (err) {
      throw new Error(
        `Unsupported model "${model}": ${err instanceof Error ? err.message : err}`,
      );
    }
  }
  logger.info("Preflight OK — model and credentials validated");

  const targetRepo = `${owner}/${repo}`;
  let knowledgeBaseConfig = getKnowledgeBaseConfig();
  if (knowledgeBaseConfig.enabled) {
    try {
      const kbHealth = await checkKnowledgeBaseHealth(knowledgeBaseConfig);
      if (!kbHealth.ok) {
        logger.warn(
          `Knowledge base disabled for this run: ${kbHealth.reason ?? "health check failed"}`,
        );
        knowledgeBaseConfig = { ...knowledgeBaseConfig, enabled: false };
      } else if (kbHealth.reason) {
        logger.info(`Knowledge base preflight: ${kbHealth.reason}`);
      } else {
        logger.info(
          `Knowledge base preflight OK (branch: ${
            kbHealth.branchExists
              ? knowledgeBaseConfig.branch
              : "will bootstrap on first save"
          }, writable: ${kbHealth.writable})`,
        );
      }
    } catch (err) {
      logger.warn(`Knowledge base preflight failed, disabling tools: ${err}`);
      knowledgeBaseConfig = { ...knowledgeBaseConfig, enabled: false };
    }
  }
  // --- End preflight ---
  // Setup workspace
  const { workspace, targetBranch, diffBaseSha, isTemporary } =
    await setupWorkspace({
      platform,
      owner,
      repo,
      prNumber: String(prNumber),
      host,
      workingDir: workspaceDir ?? undefined,
      reuse: workspaceDir != null,
    });

  const workspacePath = workspace;

  try {
    // Fetch PR metadata
    let mrMetadata: MrMetadata | null = null;
    if (platform === "gitlab") {
      try {
        mrMetadata = await fetchGitlabMrInfo(owner, repo, prNumber, host, {
          includeComments: true,
        });
      } catch (err) {
        logger.warn(`Failed to fetch GitLab metadata: ${err}`);
      }
    } else if (platform === "github") {
      try {
        const githubRaw = await fetchGithubPrInfo(owner, repo, prNumber);
        mrMetadata = normalizeGithubMetadata(githubRaw);
      } catch (err) {
        logger.warn(`Failed to fetch GitHub metadata: ${err}`);
      }
    }

    // Build prompt (always uses JSON template; rendered to markdown post-hoc)
    const prompt = buildPrReviewPrompt({
      prUrl,
      platform,
      targetBranch,
      diffBaseSha,
      mrMetadata,
      customInstructions: customPrompt,
      customPromptFile: promptFile,
    });

    const startTime = Date.now();
    const settingsManager = SettingsManager.inMemory({
      compaction: { enabled: false },
    });
    const skillPaths = [
      join(workspacePath, ".pi", "skills"),
      join(workspacePath, ".hodor", "skills"),
    ].filter((p) => existsSync(p));
    const resourceLoader = new DefaultResourceLoader({
      cwd: workspacePath,
      settingsManager,
      systemPrompt: REVIEW_SYSTEM_PROMPT,
      appendSystemPrompt: "",
      noExtensions: true,
      noSkills: true,
      noPromptTemplates: true,
      noThemes: true,
      additionalSkillPaths: skillPaths,
      agentsFilesOverride: () => ({ agentsFiles: [] }),
    });
    await resourceLoader.reload();
    const { skills, diagnostics: skillDiagnostics } =
      resourceLoader.getSkills();
    if (skills.length > 0) {
      logger.info(`Discovered ${skills.length} repository skill(s)`);
      for (const skill of skills) {
        logger.info(`Found skill: ${skill.name} (${skill.filePath})`);
      }
    }
    for (const diagnostic of skillDiagnostics) {
      const path = diagnostic.path ? ` (${diagnostic.path})` : "";
      logger.warn(`Skill diagnostic: ${diagnostic.message}${path}`);
    }

    let submittedReview: ReviewOutput | null = null;
    let kbQueryCalls = 0;
    let kbNoMatchResponses = 0;
    let submitReviewCalls = 0;
    const submitReviewTool: ToolDefinition = {
      name: "submit_review",
      label: "Submit Review",
      description:
        "Submit the final structured review after the analysis is complete.",
      parameters: SUBMIT_REVIEW_SCHEMA,
      execute: async (_toolCallId, params, _signal, _onUpdate, _ctx) => {
        submitReviewCalls++;
        if (submittedReview) {
          logger.warn(
            "Agent called submit_review more than once; ignoring duplicate submission",
          );
          return {
            content: [
              {
                type: "text",
                text: "Review already submitted. Do not call submit_review again.",
              },
            ],
            details: { ignoredDuplicate: true },
          };
        }

        let candidate: ReviewOutput;
        try {
          candidate = validateReviewOutput(params as ReviewOutput);
        } catch (err) {
          const message = err instanceof Error ? err.message : String(err);
          logger.warn(`Rejected submit_review payload: ${message}`);
          return {
            content: [
              {
                type: "text",
                text: `Invalid submit_review payload: ${message}. Fix the payload and call submit_review again once.`,
              },
            ],
            details: { ok: false, reason: message },
          };
        }

        if (kbQueryCalls > 0 && kbNoMatchResponses > 0 && !candidate.kb_question_closure?.trim()) {
          return {
            content: [
              {
                type: "text",
                text: "submit_review requires `kb_question_closure` because earlier `query_knowledge_base` calls returned no matches. Add an evidence-backed closure note and call submit_review again.",
              },
            ],
            details: {
              ok: false,
              reason: "missing kb_question_closure after no-match knowledge queries",
              kbQueryCalls,
              kbNoMatchResponses,
            },
          };
        }

        submittedReview = candidate;
        logger.info(
          `Received structured review via submit_review (${submittedReview.findings.length} finding(s))`,
        );
        return {
          content: [
            {
              type: "text",
              text: "Review received. Do not output the review as normal text.",
            },
          ],
          details: {},
        };
      },
    };

    const queryKnowledgeBaseTool: ToolDefinition = {
      name: "query_knowledge_base",
      label: "Query Knowledge Base",
      description:
        "Search persisted review learnings for architecture, call chains, and durable patterns.",
      parameters: QUERY_KNOWLEDGE_BASE_SCHEMA,
      execute: async (_toolCallId, params, _signal, _onUpdate, _ctx) => {
        kbQueryCalls++;
        const result = await queryKnowledgeBase(
          knowledgeBaseConfig,
          targetRepo,
          params as {
            query: string;
            paths?: string[];
            symbols?: string[];
            max_results?: number;
          },
        );
        if (!result.ok) {
          return {
            content: [
              {
                type: "text",
                text: `query_knowledge_base unavailable: ${result.reason ?? "unknown error"}`,
              },
            ],
            details: { ok: false, reason: result.reason },
          };
        }

        if (result.matches.length === 0) {
          kbNoMatchResponses++;
          return {
            content: [
              {
                type: "text",
                text: "No prior durable learnings matched this query.",
              },
            ],
            details: { ok: true, matches: [] },
          };
        }

        const summary = result.matches
          .map(
            (match, index) =>
              `${index + 1}. [${match.category}] ${match.learning} (confidence: ${match.confidence})`,
          )
          .join("\n");
        return {
          content: [
            {
              type: "text",
              text: `Matched prior learnings:\n${summary}`,
            },
          ],
          details: { ok: true, matches: result.matches },
        };
      },
    };

    const saveKnowledgeBaseTool: ToolDefinition = {
      name: "save_knowledge_base",
      label: "Save Knowledge Base",
      description:
        "Persist a high-signal learning. Category must be architecture, coding_pattern, service_call_chain, or fundamental_design.",
      parameters: SAVE_KNOWLEDGE_BASE_SCHEMA,
      execute: async (_toolCallId, params, _signal, _onUpdate, _ctx) => {
        const result = await saveKnowledgeBase(
          knowledgeBaseConfig,
          targetRepo,
          params as {
            learning: string;
            category:
              | "architecture"
              | "coding_pattern"
              | "service_call_chain"
              | "fundamental_design";
            evidence: string;
            stability: "low" | "medium" | "high";
            scope_tags: string[];
            paths?: string[];
            symbols?: string[];
            source_pr?: string;
          },
        );
        if (!result.ok) {
          return {
            content: [
              {
                type: "text",
                text: `save_knowledge_base skipped: ${result.reason ?? "not saved"}`,
              },
            ],
            details: result,
          };
        }
        return {
          content: [
            {
              type: "text",
              text: `Learning persisted (${result.status}) with id ${result.entryId ?? "unknown"}.`,
            },
          ],
          details: result,
        };
      },
    };

    const { session } = await createAgentSession({
      cwd: workspacePath,
      model: piModel,
      thinkingLevel,
      tools: [
        createReadTool(workspacePath),
        createBashTool(workspacePath),
        createGrepTool(workspacePath),
        createFindTool(workspacePath),
        createLsTool(workspacePath),
      ],
      customTools: [
        queryKnowledgeBaseTool,
        saveKnowledgeBaseTool,
        submitReviewTool,
      ],
      sessionManager: SessionManager.inMemory(),
      settingsManager,
      resourceLoader,
    });

    // Subscribe to agent events for progress + metrics tracking
    let turnCount = 0;
    let toolCallCount = 0;

    /** Extract human-readable summary from tool args */
    function formatToolArgs(_toolName: string, args: unknown): string {
      if (typeof args === "string") return args.slice(0, 200);
      const obj = args as Record<string, unknown> | undefined;
      if (!obj) return "";
      // bash tool: show the command, strip workspace prefix
      if (obj.command) {
        return String(obj.command)
          .replace(
            new RegExp(
              `cd ${workspacePath.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")} && `,
            ),
            "",
          )
          .slice(0, 200);
      }
      // grep/find: show pattern + path
      if (obj.pattern) {
        const path = obj.path ? ` in ${obj.path}` : "";
        return `${obj.pattern}${path}`;
      }
      // read/ls: show the path
      if (obj.path || obj.file_path) return String(obj.path ?? obj.file_path);
      return JSON.stringify(obj).slice(0, 200);
    }

    /** Extract text content from tool result */
    function formatToolResult(result: unknown): string {
      if (typeof result === "string") return result;
      const obj = result as Record<string, unknown> | undefined;
      if (!obj) return "";
      // pi-sdk wraps results as {content: [{type: "text", text: "..."}]}
      const content = obj.content as
        | Array<{ type?: string; text?: string }>
        | undefined;
      if (Array.isArray(content)) {
        return content
          .filter((c) => c.type === "text" && c.text)
          .map((c) => c.text)
          .join("\n");
      }
      return JSON.stringify(result)?.slice(0, 500) ?? "";
    }

    session.subscribe((event) => {
      switch (event.type) {
        case "agent_start":
          onEvent?.({ type: "agent_start" });
          break;
        case "agent_end":
          onEvent?.({ type: "agent_end" });
          break;
        case "turn_start":
          turnCount++;
          onEvent?.({ type: "turn_start", turnIndex: turnCount });
          break;
        case "turn_end":
          onEvent?.({ type: "turn_end", turnIndex: turnCount });
          break;
        case "tool_execution_start":
          toolCallCount++;
          onEvent?.({
            type: "tool_start",
            toolName: event.toolName,
            toolArgs: formatToolArgs(event.toolName, event.args),
          });
          break;
        case "tool_execution_end":
          onEvent?.({
            type: "tool_end",
            toolName: event.toolName,
            isError: event.isError,
            result: formatToolResult(event.result),
          });
          break;
        case "message_start":
          onEvent?.({ type: "thinking" });
          break;
        case "message_update": {
          const msgEvent = (event as Record<string, unknown>)
            .assistantMessageEvent as
            | { type: string; delta?: string }
            | undefined;
          if (!msgEvent?.delta) break;
          if (msgEvent.type === "text_delta") {
            onEvent?.({ type: "text_delta", delta: msgEvent.delta });
          } else if (msgEvent.type === "thinking_delta") {
            onEvent?.({ type: "thinking_delta", delta: msgEvent.delta });
          }
          break;
        }
      }
    });

    logger.info("Sending prompt to agent...");
    await session.prompt(prompt);

    // Check for agent errors (pi-ai swallows LLM errors into state.error)
    const agentError = (session as unknown as { state: { error?: string } })
      .state?.error;
    if (agentError) {
      throw new Error(`LLM request failed: ${agentError}`);
    }

    if (!submittedReview) {
      const rawText = session.getLastAssistantText() ?? "";
      if (rawText) {
        logger.debug(
          `Last assistant text without submit_review (first 500 chars): ${rawText.slice(0, 500)}`,
        );
      } else {
        const messages = (
          session as unknown as { state: { messages: unknown[] } }
        ).state?.messages;
        const lastMsg = messages?.[messages.length - 1];
        logger.debug(`Last message: ${JSON.stringify(lastMsg)?.slice(0, 500)}`);
      }
      if (submitReviewCalls > 0) {
        throw new Error(
          "Agent called submit_review but did not provide a valid review payload",
        );
      }
      throw new Error("Agent did not call submit_review");
    }

    const review = submittedReview as ReviewOutput;
    if (submitReviewCalls > 1) {
      logger.warn(
        `Agent called submit_review ${submitReviewCalls} times; using the first valid submission`,
      );
    }
    logger.info(
      `Captured ${review.findings.length} finding(s), verdict: ${review.overall_correctness}`,
    );

    const durationSeconds = (Date.now() - startTime) / 1000;
    logger.info(`Review complete (${review.findings.length} finding(s))`);

    // Aggregate usage from all assistant messages
    interface MsgUsage {
      input: number;
      output: number;
      cacheRead: number;
      cacheWrite: number;
      totalTokens: number;
      cost: { total: number };
    }
    interface AssistantMsg {
      role: string;
      usage?: MsgUsage;
    }

    const allMessages =
      (session as unknown as { state: { messages: AssistantMsg[] } }).state
        ?.messages ?? [];

    let inputTokens = 0;
    let outputTokens = 0;
    let cacheReadTokens = 0;
    let cacheWriteTokens = 0;
    let totalTokens = 0;
    let cost = 0;

    for (const msg of allMessages) {
      if (msg.role === "assistant" && msg.usage) {
        inputTokens += msg.usage.input ?? 0;
        outputTokens += msg.usage.output ?? 0;
        cacheReadTokens += msg.usage.cacheRead ?? 0;
        cacheWriteTokens += msg.usage.cacheWrite ?? 0;
        totalTokens += msg.usage.totalTokens ?? 0;
        cost += msg.usage.cost?.total ?? 0;
      }
    }

    const metrics: ReviewMetrics = {
      inputTokens,
      outputTokens,
      cacheReadTokens,
      cacheWriteTokens,
      totalTokens,
      cost,
      turns: turnCount,
      toolCalls: toolCallCount,
      durationSeconds: Math.round(durationSeconds),
    };
    printMetrics(metrics);

    let metricsFooter: string | null = null;
    if (includeMetricsFooter) {
      metricsFooter = formatMetricsMarkdown(metrics);
    }

    const repoUrl = `https://${host}/${owner}/${repo}`;
    const renderContext: RenderContext = {
      platform,
      repoUrl,
      sourceRef: mrMetadata?.source_branch,
    };

    return { review, metricsFooter, renderContext };
  } finally {
    // Restore mutated env vars
    for (const [key, val] of Object.entries(envSnapshot)) {
      if (val === undefined) {
        delete process.env[key];
      } else {
        process.env[key] = val;
      }
    }

    if (cleanup && isTemporary) {
      logger.info("Cleaning up workspace...");
      await cleanupWorkspace(workspacePath);
    }
  }
}
