import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { logger } from "./utils/logger.js";
import { exec } from "./utils/exec.js";
import {
  fetchGithubPrInfo,
  normalizeGithubMetadata,
} from "./github.js";
import {
  fetchGitlabMrInfo,
  postGitlabMrComment,
} from "./gitlab.js";
import { setupWorkspace, cleanupWorkspace } from "./workspace.js";
import { buildPrReviewPrompt } from "./prompt.js";
import { parseModelString, mapReasoningEffort, getApiKey } from "./model.js";
import { formatMetricsMarkdown, printMetrics } from "./metrics.js";
import { REVIEW_SYSTEM_PROMPT } from "./system-prompt.js";
import type {
  Platform,
  ParsedPrUrl,
  ReviewMetrics,
  PostCommentResult,
  MrMetadata,
} from "./types.js";

export interface AgentProgressEvent {
  type: "tool_start" | "tool_end" | "thinking" | "turn_start" | "turn_end" | "agent_start" | "agent_end";
  toolName?: string;
  toolArgs?: string;
  isError?: boolean;
  turnIndex?: number;
}

export function detectPlatform(prUrl: string): Platform {
  const url = new URL(prUrl);
  const hostname = url.hostname;
  if (prUrl.includes("/-/merge_requests/") || hostname.includes("gitlab")) {
    return "gitlab";
  }
  if (prUrl.includes("/pull/") || hostname.includes("github")) {
    return "github";
  }
  logger.debug(`Unknown platform for URL ${prUrl}, defaulting to GitHub`);
  return "github";
}

export function parsePrUrl(prUrl: string): ParsedPrUrl {
  const url = new URL(prUrl);
  const pathParts = url.pathname.split("/").filter(Boolean);
  const host = url.host;

  // GitHub format: /owner/repo/pull/123
  if (pathParts.length >= 4 && pathParts[2] === "pull") {
    return {
      owner: pathParts[0],
      repo: pathParts[1],
      prNumber: parseInt(pathParts[3], 10),
      host,
    };
  }

  // GitLab format: /group/subgroup/repo/-/merge_requests/123
  const mrIndex = pathParts.indexOf("merge_requests");
  if (mrIndex >= 0) {
    if (mrIndex < 2 || mrIndex + 1 >= pathParts.length) {
      throw new Error(
        `Invalid GitLab MR URL format: ${prUrl}. Expected .../-/merge_requests/<number>`,
      );
    }
    if (pathParts[mrIndex - 1] !== "-") {
      throw new Error(
        `Invalid GitLab MR URL format: ${prUrl}. Missing '/-/' segment before merge_requests.`,
      );
    }

    const repo = pathParts[mrIndex - 2];
    const ownerParts = pathParts.slice(0, mrIndex - 2);
    const owner =
      ownerParts.length > 0 ? ownerParts.join("/") : pathParts[0];
    const prNumber = parseInt(pathParts[mrIndex + 1], 10);
    return { owner, repo, prNumber, host };
  }

  throw new Error(
    `Invalid PR/MR URL format: ${prUrl}. Expected GitHub pull request or GitLab merge request URL.`,
  );
}

export async function postReviewComment(opts: {
  prUrl: string;
  reviewText: string;
  model?: string | null;
  metricsFooter?: string | null;
}): Promise<PostCommentResult> {
  const { prUrl, reviewText, model, metricsFooter } = opts;
  const platform = detectPlatform(prUrl);
  logger.info(`Posting comment to ${platform} PR/MR: ${prUrl}`);

  let parsed: ParsedPrUrl;
  try {
    parsed = parsePrUrl(prUrl);
  } catch (err) {
    return { success: false, error: String(err) };
  }

  let body = reviewText;
  if (model) {
    body = `${body}\n\n---\n\nReview generated by Hodor (model: \`${model}\`)`;
  }
  if (metricsFooter) {
    body = `${body}\n\n${metricsFooter}`;
  }

  try {
    if (platform === "github") {
      await exec("gh", [
        "pr",
        "review",
        String(parsed.prNumber),
        "--repo",
        `${parsed.owner}/${parsed.repo}`,
        "--comment",
        "--body",
        body,
      ]);
      logger.info(`Successfully posted review to GitHub PR #${parsed.prNumber}`);
      return { success: true, platform: "github", prNumber: parsed.prNumber };
    } else {
      await postGitlabMrComment(
        parsed.owner,
        parsed.repo,
        parsed.prNumber,
        body,
        parsed.host,
      );
      logger.info(
        `Successfully posted review to GitLab MR !${parsed.prNumber}`,
      );
      return {
        success: true,
        platform: "gitlab",
        mrNumber: parsed.prNumber,
      };
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.error(`Failed to post comment: ${msg}`);
    return { success: false, error: msg };
  }
}

/**
 * Discover skills from workspace (.hodor/skills/*.md and .cursorrules).
 */
function tryLoadSkill(filePath: string, label: string): string | null {
  try {
    const content = readFileSync(filePath, "utf-8");
    if (content.trim()) {
      logger.info(`Found skill: ${label}`);
      return content;
    }
  } catch {
    // File doesn't exist or can't be read — skip silently
  }
  return null;
}

function discoverSkills(workspace: string): string[] {
  const skills: string[] = [];

  // Check .cursorrules + common skill files
  for (const name of [".cursorrules", "AGENTS.md", "agents.md", "claude.md", "gemini.md"]) {
    const content = tryLoadSkill(join(workspace, name), name);
    if (content) skills.push(content);
  }

  // Check .hodor/skills/*.md
  try {
    const skillsDir = join(workspace, ".hodor", "skills");
    const files = readdirSync(skillsDir).filter((f) => f.endsWith(".md")).sort();
    for (const file of files) {
      const content = tryLoadSkill(join(skillsDir, file), `.hodor/skills/${file}`);
      if (content) skills.push(content);
    }
  } catch {
    // .hodor/skills/ doesn't exist — skip
  }

  return skills;
}

export async function reviewPr(opts: {
  prUrl: string;
  model?: string;
  reasoningEffort?: string;
  customPrompt?: string | null;
  promptFile?: string | null;
  cleanup?: boolean;
  workspaceDir?: string | null;
  outputFormat?: "markdown" | "json";
  includeMetricsFooter?: boolean;
  onEvent?: (event: AgentProgressEvent) => void;
}): Promise<{ reviewText: string; metricsFooter: string | null }> {
  const {
    prUrl,
    model = "anthropic/claude-sonnet-4-5-20250929",
    reasoningEffort,
    customPrompt,
    promptFile,
    cleanup = true,
    workspaceDir,
    outputFormat = "markdown",
    includeMetricsFooter = false,
    onEvent,
  } = opts;

  logger.info(`Starting PR review for: ${prUrl}`);

  // Parse PR URL
  const { owner, repo, prNumber, host } = parsePrUrl(prUrl);
  const platform = detectPlatform(prUrl);
  logger.info(`Platform: ${platform}, Repo: ${owner}/${repo}, PR: ${prNumber}, Host: ${host}`);

  // --- Preflight: validate model + credentials before any expensive I/O ---
  const parsed = parseModelString(model);
  const thinkingLevel = mapReasoningEffort(reasoningEffort);

  // Resolve API key (throws if missing for non-bedrock providers)
  const apiKey = getApiKey(model);

  // For bedrock, verify AWS credentials are present
  if (parsed.provider === "amazon-bedrock") {
    const hasAwsCreds =
      process.env.AWS_ACCESS_KEY_ID ||
      process.env.AWS_PROFILE ||
      process.env.AWS_WEB_IDENTITY_TOKEN_FILE; // EKS/IRSA
    if (!hasAwsCreds) {
      throw new Error(
        "Bedrock model requires AWS credentials. Set AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY, " +
        "AWS_PROFILE, or run from an environment with an IAM role.",
      );
    }
  }

  // Set API key in environment for pi-ai early so session creation can use it
  if (apiKey) {
    if (parsed.provider === "anthropic") {
      process.env.ANTHROPIC_API_KEY = apiKey;
    } else if (parsed.provider === "openai") {
      process.env.OPENAI_API_KEY = apiKey;
    }
  }

  // Import pi SDK
  const {
    createAgentSession,
    SessionManager,
    SettingsManager,
    createReadTool,
    createBashTool,
    createGrepTool,
    createFindTool,
    createLsTool,
    createExtensionRuntime,
  } = await import("@mariozechner/pi-coding-agent");
  const { getModel } = await import("@mariozechner/pi-ai");

  // Resolve model — use registry for known models, construct manually for custom ARNs
  let piModel: ReturnType<typeof getModel>;
  if (parsed.modelId.startsWith("arn:")) {
    // Custom bedrock ARN (inference profile, cross-region, etc.)
    // Extract region from ARN: arn:aws:bedrock:<region>:<account>:...
    const arnParts = parsed.modelId.split(":");
    const region = arnParts.length >= 4 ? arnParts[3] : "us-east-1";
    // Set AWS_REGION so the BedrockRuntimeClient uses the correct endpoint
    if (!process.env.AWS_REGION && !process.env.AWS_DEFAULT_REGION) {
      process.env.AWS_REGION = region;
    }
    piModel = {
      id: parsed.modelId,
      name: parsed.modelId,
      api: "bedrock-converse-stream",
      provider: "amazon-bedrock",
      baseUrl: `https://bedrock-runtime.${region}.amazonaws.com`,
      reasoning: false,
      input: ["text"] as ("text" | "image")[],
      cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
      contextWindow: 200000,
      maxTokens: 16384,
    } as ReturnType<typeof getModel>;
    logger.info(`Custom bedrock ARN model — region: ${region}`);
  } else {
    try {
      piModel = getModel(parsed.provider as "anthropic", parsed.modelId as never);
    } catch (err) {
      throw new Error(
        `Unsupported model "${model}": ${err instanceof Error ? err.message : err}`,
      );
    }
  }
  logger.info("Preflight OK — model and credentials validated");

  // --- End preflight ---

  // Setup workspace
  const { workspace, targetBranch, diffBaseSha } = await setupWorkspace({
    platform,
    owner,
    repo,
    prNumber: String(prNumber),
    host,
    workingDir: workspaceDir ?? undefined,
    reuse: workspaceDir != null,
  });

  const workspacePath = workspace;

  try {
    // Discover skills
    const skills = discoverSkills(workspacePath);
    if (skills.length > 0) {
      logger.info(`Discovered ${skills.length} repository skill(s)`);
    }

    // Fetch PR metadata
    let mrMetadata: MrMetadata | null = null;
    if (platform === "gitlab") {
      try {
        mrMetadata = await fetchGitlabMrInfo(owner, repo, prNumber, host, {
          includeComments: true,
        });
      } catch (err) {
        logger.warn(`Failed to fetch GitLab metadata: ${err}`);
      }
    } else if (platform === "github") {
      try {
        const githubRaw = await fetchGithubPrInfo(owner, repo, prNumber);
        mrMetadata = normalizeGithubMetadata(githubRaw);
      } catch (err) {
        logger.warn(`Failed to fetch GitHub metadata: ${err}`);
      }
    }

    // Build prompt
    const prompt = buildPrReviewPrompt({
      prUrl,
      owner,
      repo,
      prNumber: String(prNumber),
      platform,
      targetBranch,
      diffBaseSha,
      mrMetadata,
      customInstructions: customPrompt,
      customPromptFile: promptFile,
      outputFormat,
    });

    const startTime = Date.now();

    // Build system prompt with skills injected
    let systemPrompt = REVIEW_SYSTEM_PROMPT;
    if (skills.length > 0) {
      systemPrompt +=
        "\n\n<REPOSITORY_SKILLS>\n" +
        skills.join("\n\n---\n\n") +
        "\n</REPOSITORY_SKILLS>";
    }

    const { session } = await createAgentSession({
      cwd: workspacePath,
      model: piModel,
      thinkingLevel,
      tools: [
        createReadTool(workspacePath),
        createBashTool(workspacePath),
        createGrepTool(workspacePath),
        createFindTool(workspacePath),
        createLsTool(workspacePath),
      ],
      sessionManager: SessionManager.inMemory(),
      settingsManager: SettingsManager.inMemory({
        compaction: { enabled: false },
      }),
      resourceLoader: {
        getSystemPrompt: () => systemPrompt,
        getExtensions: () => ({
          extensions: [],
          errors: [],
          runtime: createExtensionRuntime(),
        }),
        getSkills: () => ({ skills: [], diagnostics: [] }),
        getPrompts: () => ({ prompts: [], diagnostics: [] }),
        getThemes: () => ({ themes: [], diagnostics: [] }),
        getAgentsFiles: () => ({ agentsFiles: [] }),
        getAppendSystemPrompt: () => [],
        getPathMetadata: () => new Map(),
        extendResources: () => {},
        reload: async () => {},
      },
    });

    // Subscribe to agent events for progress + metrics tracking
    let turnCount = 0;
    let toolCallCount = 0;
    session.subscribe((event) => {
      switch (event.type) {
        case "agent_start":
          onEvent?.({ type: "agent_start" });
          break;
        case "agent_end":
          onEvent?.({ type: "agent_end" });
          break;
        case "turn_start":
          turnCount++;
          onEvent?.({ type: "turn_start", turnIndex: turnCount });
          break;
        case "turn_end":
          onEvent?.({ type: "turn_end", turnIndex: turnCount });
          break;
        case "tool_execution_start":
          toolCallCount++;
          onEvent?.({
            type: "tool_start",
            toolName: event.toolName,
            toolArgs: typeof event.args === "string"
              ? event.args.slice(0, 120)
              : JSON.stringify(event.args).slice(0, 120),
          });
          break;
        case "tool_execution_end":
          onEvent?.({
            type: "tool_end",
            toolName: event.toolName,
            isError: event.isError,
          });
          break;
        case "message_start":
          onEvent?.({ type: "thinking" });
          break;
      }
    });

    logger.info("Sending prompt to agent...");
    await session.prompt(prompt);

    // Check for agent errors (pi-ai swallows LLM errors into state.error)
    const agentError = (session as unknown as { state: { error?: string } }).state?.error;
    if (agentError) {
      throw new Error(`LLM request failed: ${agentError}`);
    }

    // Extract review text from last assistant message
    const reviewText = session.getLastAssistantText() ?? "";

    if (!reviewText) {
      const messages = (session as unknown as { state: { messages: unknown[] } }).state?.messages;
      const lastMsg = messages?.[messages.length - 1];
      logger.debug(`Last message: ${JSON.stringify(lastMsg)?.slice(0, 500)}`);
      throw new Error("Agent did not produce any review content");
    }

    const durationSeconds = (Date.now() - startTime) / 1000;
    logger.info(`Review complete (${reviewText.length} chars)`);

    // Aggregate usage from all assistant messages
    interface MsgUsage {
      input: number;
      output: number;
      cacheRead: number;
      cacheWrite: number;
      totalTokens: number;
      cost: { total: number };
    }
    interface AssistantMsg {
      role: string;
      usage?: MsgUsage;
    }

    const allMessages = (
      session as unknown as { state: { messages: AssistantMsg[] } }
    ).state?.messages ?? [];

    let inputTokens = 0;
    let outputTokens = 0;
    let cacheReadTokens = 0;
    let cacheWriteTokens = 0;
    let totalTokens = 0;
    let cost = 0;

    for (const msg of allMessages) {
      if (msg.role === "assistant" && msg.usage) {
        inputTokens += msg.usage.input ?? 0;
        outputTokens += msg.usage.output ?? 0;
        cacheReadTokens += msg.usage.cacheRead ?? 0;
        cacheWriteTokens += msg.usage.cacheWrite ?? 0;
        totalTokens += msg.usage.totalTokens ?? 0;
        cost += msg.usage.cost?.total ?? 0;
      }
    }

    const metrics: ReviewMetrics = {
      inputTokens,
      outputTokens,
      cacheReadTokens,
      cacheWriteTokens,
      totalTokens,
      cost,
      turns: turnCount,
      toolCalls: toolCallCount,
      durationSeconds: Math.round(durationSeconds),
    };
    printMetrics(metrics);

    let metricsFooter: string | null = null;
    if (includeMetricsFooter) {
      metricsFooter = formatMetricsMarkdown(metrics);
    }

    return { reviewText, metricsFooter };
  } finally {
    if (cleanup && !workspaceDir) {
      logger.info("Cleaning up workspace...");
      await cleanupWorkspace(workspacePath);
    }
  }
}
