import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { detectPlatform, parsePrUrl } from "./agent.js";
import {
  fetchGithubIssueComments,
  fetchGithubReviewComments,
  type GithubIssueComment,
} from "./github.js";
import { fetchGitlabMrInfo } from "./gitlab.js";
import { parseModelString, getApiKey } from "./model.js";
import {
  isHighSignalCandidate,
  saveKnowledgeBase,
  type KnowledgeBaseConfig,
  type SaveKnowledgeInput,
} from "./knowledge.js";
import { logger } from "./utils/logger.js";
import type { Platform, NoteEntry } from "./types.js";

const HODOR_SIGNATURE = "Review generated by Hodor";

export interface FeedbackComment {
  body: string;
  author: string;
  created_at: string;
}

export interface HodorReviewComment {
  body: string;
  created_at: string;
  platform: Platform;
}

export interface FeedbackContext {
  hodorReview: HodorReviewComment;
  feedbackComments: FeedbackComment[];
  /** PR discussion that happened before Hodor's review — provided as LLM context only. */
  preReviewComments: FeedbackComment[];
}

export interface FeedbackExtractionResult {
  extracted: number;
  saved: number;
  updated: number;
  rejected: number;
  errors: string[];
  learnings: string[];
  llmMetrics?: {
    inputTokens: number;
    outputTokens: number;
    cacheReadTokens: number;
    cacheWriteTokens: number;
    totalTokens: number;
    cost: number;
    durationSeconds: number;
  };
}

function getTemplatesDir(): string {
  const currentDir = dirname(fileURLToPath(import.meta.url));
  return resolve(currentDir, "..", "templates");
}

function loadFeedbackTemplate(): string {
  const templateFile = resolve(getTemplatesDir(), "feedback-extraction.md");
  return readFileSync(templateFile, "utf-8");
}

function buildFeedbackPrompt(opts: {
  prUrl: string;
  targetRepo: string;
  hodorReview: string;
  feedbackComments: string;
  preReviewContext: string;
}): string {
  const template = loadFeedbackTemplate();
  return template
    .replace(/\{pr_url\}/g, opts.prUrl)
    .replace(/\{target_repo\}/g, opts.targetRepo)
    .replace(/\{hodor_review\}/g, opts.hodorReview)
    .replace(/\{feedback_comments\}/g, opts.feedbackComments)
    .replace(/\{pre_review_context\}/g, opts.preReviewContext);
}

/**
 * Find Hodor's review comment among GitHub issue comments and review submissions.
 * Returns Hodor's review, post-review feedback, and pre-review discussion.
 */
async function findGithubHodorReview(
  owner: string,
  repo: string,
  prNumber: number,
): Promise<{
  review: HodorReviewComment;
  feedbackComments: FeedbackComment[];
  preReviewComments: FeedbackComment[];
} | null> {
  const [issueComments, reviewComments] = await Promise.all([
    fetchGithubIssueComments(owner, repo, prNumber),
    fetchGithubReviewComments(owner, repo, prNumber),
  ]);

  // Check review submissions first (Hodor uses `gh pr review --comment`)
  const hodorReview = reviewComments.find((r) =>
    r.body.includes(HODOR_SIGNATURE),
  );

  if (hodorReview) {
    const reviewTime = hodorReview.submitted_at;
    const { before, after } = partitionIssueComments(issueComments, reviewTime);

    // Also include review submissions posted after Hodor's review by other authors
    for (const r of reviewComments) {
      if (
        r.id !== hodorReview.id &&
        !r.body.includes(HODOR_SIGNATURE) &&
        r.submitted_at > reviewTime &&
        r.body.trim().length > 0
      ) {
        after.push({
          body: r.body,
          author: r.author.username ?? r.author.name ?? "unknown",
          created_at: r.submitted_at,
        });
      }
    }

    after.sort((a, b) => a.created_at.localeCompare(b.created_at));

    return {
      review: {
        body: hodorReview.body,
        created_at: reviewTime,
        platform: "github",
      },
      feedbackComments: after,
      preReviewComments: before,
    };
  }

  // Fallback: check issue comments
  const hodorIssueComment = issueComments.find((c) =>
    c.body.includes(HODOR_SIGNATURE),
  );

  if (hodorIssueComment) {
    const reviewTime = hodorIssueComment.created_at;
    const remaining = issueComments.filter(
      (c) => c.id !== hodorIssueComment.id,
    );
    const { before, after } = partitionIssueComments(remaining, reviewTime);

    return {
      review: {
        body: hodorIssueComment.body,
        created_at: reviewTime,
        platform: "github",
      },
      feedbackComments: after,
      preReviewComments: before,
    };
  }

  return null;
}

/**
 * Split issue comments into pre-review and post-review buckets.
 */
function partitionIssueComments(
  comments: GithubIssueComment[],
  reviewTimestamp: string,
): { before: FeedbackComment[]; after: FeedbackComment[] } {
  const before: FeedbackComment[] = [];
  const after: FeedbackComment[] = [];

  for (const c of comments) {
    if (c.body.includes(HODOR_SIGNATURE) || c.body.trim().length === 0)
      continue;
    const fc: FeedbackComment = {
      body: c.body,
      author: c.author.username ?? c.author.name ?? "unknown",
      created_at: c.created_at,
    };
    if (c.created_at > reviewTimestamp) {
      after.push(fc);
    } else {
      before.push(fc);
    }
  }

  before.sort((a, b) => a.created_at.localeCompare(b.created_at));
  after.sort((a, b) => a.created_at.localeCompare(b.created_at));
  return { before, after };
}

/**
 * Find Hodor's review comment among GitLab MR notes.
 */
async function findGitlabHodorReview(
  owner: string,
  repo: string,
  mrNumber: number,
  host?: string | null,
): Promise<{
  review: HodorReviewComment;
  feedbackComments: FeedbackComment[];
  preReviewComments: FeedbackComment[];
} | null> {
  const mrInfo = await fetchGitlabMrInfo(owner, repo, mrNumber, host, {
    includeComments: true,
  });

  const notes = mrInfo.Notes ?? [];
  const hodorNote = notes.find(
    (n) => n.body?.includes(HODOR_SIGNATURE) && !n.system,
  );

  if (!hodorNote || !hodorNote.created_at) return null;

  const reviewTime = hodorNote.created_at;
  const { before, after } = partitionGitlabNotes(notes, reviewTime, hodorNote);

  return {
    review: {
      body: hodorNote.body ?? "",
      created_at: reviewTime,
      platform: "gitlab",
    },
    feedbackComments: after,
    preReviewComments: before,
  };
}

function partitionGitlabNotes(
  notes: NoteEntry[],
  reviewTimestamp: string,
  hodorNote: NoteEntry,
): { before: FeedbackComment[]; after: FeedbackComment[] } {
  const before: FeedbackComment[] = [];
  const after: FeedbackComment[] = [];

  for (const n of notes) {
    if (n === hodorNote || n.system) continue;
    if (n.body?.includes(HODOR_SIGNATURE)) continue;
    if ((n.body ?? "").trim().length === 0) continue;

    const fc: FeedbackComment = {
      body: n.body ?? "",
      author: n.author?.username ?? n.author?.name ?? "unknown",
      created_at: n.created_at ?? "",
    };

    if ((n.created_at ?? "") > reviewTimestamp) {
      after.push(fc);
    } else {
      before.push(fc);
    }
  }

  before.sort((a, b) => a.created_at.localeCompare(b.created_at));
  after.sort((a, b) => a.created_at.localeCompare(b.created_at));
  return { before, after };
}

/**
 * Fetch the feedback context for a PR/MR: Hodor's review, post-review feedback,
 * and pre-review discussion for additional context.
 */
export async function fetchFeedbackContext(
  prUrl: string,
): Promise<FeedbackContext | null> {
  const platform = detectPlatform(prUrl);
  const parsed = parsePrUrl(prUrl);

  if (platform === "github") {
    const result = await findGithubHodorReview(
      parsed.owner,
      parsed.repo,
      parsed.prNumber,
    );
    if (!result) return null;
    return {
      hodorReview: result.review,
      feedbackComments: result.feedbackComments,
      preReviewComments: result.preReviewComments,
    };
  }

  const result = await findGitlabHodorReview(
    parsed.owner,
    parsed.repo,
    parsed.prNumber,
    parsed.host,
  );
  if (!result) return null;
  return {
    hodorReview: result.review,
    feedbackComments: result.feedbackComments,
    preReviewComments: result.preReviewComments,
  };
}

function formatCommentsForPrompt(comments: FeedbackComment[]): string {
  if (comments.length === 0) return "(none)";
  return comments
    .map((c) => `[${c.created_at}] @${c.author}:\n${c.body}`)
    .join("\n\n---\n\n");
}

export function parseFeedbackResponse(raw: string): SaveKnowledgeInput[] {
  let text = raw.trim();
  const fenceMatch = text.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
  if (fenceMatch) text = fenceMatch[1].trim();

  const parsed = JSON.parse(text);
  if (!Array.isArray(parsed)) {
    throw new Error("Feedback extraction response is not a JSON array");
  }
  return parsed.map((item: Record<string, unknown>) => ({
    learning: String(item.learning ?? ""),
    category: String(
      item.category ?? "coding_pattern",
    ) as SaveKnowledgeInput["category"],
    evidence: String(item.evidence ?? ""),
    stability: String(
      item.stability ?? "medium",
    ) as SaveKnowledgeInput["stability"],
    scope_tags: Array.isArray(item.scope_tags)
      ? item.scope_tags.map(String)
      : [],
    paths: Array.isArray(item.paths) ? item.paths.map(String) : undefined,
    symbols: Array.isArray(item.symbols) ? item.symbols.map(String) : undefined,
    source_pr: item.source_pr ? String(item.source_pr) : undefined,
  }));
}

interface UsageTotals {
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
  totalTokens: number;
  cost: number;
}

function sumUsageFromSessionMessages(messages: unknown[]): UsageTotals {
  interface MsgUsage {
    input: number;
    output: number;
    cacheRead: number;
    cacheWrite: number;
    totalTokens: number;
    cost: { total: number };
  }
  interface AssistantMsg {
    role: string;
    usage?: MsgUsage;
  }

  const all = messages as AssistantMsg[];
  let inputTokens = 0;
  let outputTokens = 0;
  let cacheReadTokens = 0;
  let cacheWriteTokens = 0;
  let totalTokens = 0;
  let cost = 0;

  for (const msg of all) {
    if (msg.role === "assistant" && msg.usage) {
      inputTokens += msg.usage.input ?? 0;
      outputTokens += msg.usage.output ?? 0;
      cacheReadTokens += msg.usage.cacheRead ?? 0;
      cacheWriteTokens += msg.usage.cacheWrite ?? 0;
      totalTokens += msg.usage.totalTokens ?? 0;
      cost += msg.usage.cost?.total ?? 0;
    }
  }

  return {
    inputTokens,
    outputTokens,
    cacheReadTokens,
    cacheWriteTokens,
    totalTokens,
    cost,
  };
}

/**
 * Resolve model string to a pi-ai model object, matching the same logic used
 * by the review command in agent.ts.
 */
async function resolvePiModel(model: string): Promise<unknown> {
  const parsed = parseModelString(model);
  const { getModel } = await import("@mariozechner/pi-ai");

  if (parsed.modelId.startsWith("arn:")) {
    const arnParts = parsed.modelId.split(":");
    const region = arnParts.length >= 4 ? arnParts[3] : "us-east-1";
    if (!process.env.AWS_REGION && !process.env.AWS_DEFAULT_REGION) {
      process.env.AWS_REGION = region;
    }
    return {
      id: parsed.modelId,
      name: parsed.modelId,
      api: "bedrock-converse-stream",
      provider: "amazon-bedrock",
      baseUrl: `https://bedrock-runtime.${region}.amazonaws.com`,
      reasoning: false,
      input: ["text"] as ("text" | "image")[],
      cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
      contextWindow: 200000,
      maxTokens: 16384,
    } as ReturnType<typeof getModel>;
  }

  try {
    const piModel = getModel(
      parsed.provider as "anthropic" | "openai",
      parsed.modelId as never,
    );
    // Verify the resolved model's provider matches what was requested,
    // since getModel may fall back to a default provider for unknown model IDs.
    const resolved = piModel as { provider?: string };
    if (resolved.provider && resolved.provider !== parsed.provider) {
      logger.warn(
        `Model "${model}" resolved to provider "${resolved.provider}" instead of "${parsed.provider}" — check if this model ID is registered in pi-ai`,
      );
    }
    return piModel;
  } catch (err) {
    throw new Error(
      `Unsupported model "${model}": ${err instanceof Error ? err.message : err}`,
    );
  }
}

/**
 * Run the full feedback learning pipeline:
 * 1. Resolve the LLM model from the model string
 * 2. Call LLM to extract learnings from the feedback
 * 3. Save learnings to the knowledge base
 */
export async function runFeedbackExtraction(opts: {
  config: KnowledgeBaseConfig;
  targetRepo: string;
  prUrl: string;
  model: string;
  feedbackContext: FeedbackContext;
  dryRun?: boolean;
}): Promise<FeedbackExtractionResult> {
  const result: FeedbackExtractionResult = {
    extracted: 0,
    saved: 0,
    updated: 0,
    rejected: 0,
    errors: [],
    learnings: [],
  };

  if (!opts.dryRun && (!opts.config.enabled || !opts.config.writeEnabled)) {
    return result;
  }

  const { feedbackContext } = opts;

  if (feedbackContext.feedbackComments.length === 0) {
    logger.info("No feedback comments found after Hodor's review");
    return result;
  }

  const modelName = process.env.HODOR_KB_EXTRACT_MODEL?.trim() || opts.model;

  // Resolve API key and set provider-specific env var so the pi-ai SDK
  // picks the correct endpoint (mirrors reviewPr in agent.ts).
  const parsed = parseModelString(modelName);
  const apiKey = getApiKey(modelName);
  const envSnapshot: Record<string, string | undefined> = {
    ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    AWS_REGION: process.env.AWS_REGION,
  };
  if (apiKey) {
    if (parsed.provider === "anthropic") {
      process.env.ANTHROPIC_API_KEY = apiKey;
    } else if (parsed.provider === "openai") {
      process.env.OPENAI_API_KEY = apiKey;
    }
  }

  const feedbackText = formatCommentsForPrompt(
    feedbackContext.feedbackComments,
  );
  const preReviewText = formatCommentsForPrompt(
    feedbackContext.preReviewComments,
  );
  const prompt = buildFeedbackPrompt({
    prUrl: opts.prUrl,
    targetRepo: opts.targetRepo,
    hodorReview: feedbackContext.hodorReview.body,
    feedbackComments: feedbackText,
    preReviewContext: preReviewText,
  });

  let candidates: SaveKnowledgeInput[];
  try {
    try {
      logger.info(`Running feedback extraction with model: ${modelName}`);
      const start = Date.now();

      const piModel = await resolvePiModel(modelName);

      const {
        createAgentSession,
        SessionManager,
        SettingsManager,
        DefaultResourceLoader,
      } = await import("@mariozechner/pi-coding-agent");

      const settingsManager = SettingsManager.inMemory({
        compaction: { enabled: false },
      });
      const resourceLoader = new DefaultResourceLoader({
        cwd: process.cwd(),
        settingsManager,
        systemPrompt:
          "You are a feedback analysis assistant. Respond only with JSON.",
        appendSystemPrompt: "",
        noExtensions: true,
        noSkills: true,
        noPromptTemplates: true,
        noThemes: true,
        additionalSkillPaths: [],
        agentsFilesOverride: () => ({ agentsFiles: [] }),
      });
      await resourceLoader.reload();

      const { session } = await createAgentSession({
        cwd: process.cwd(),
        model: piModel as ReturnType<
          typeof import("@mariozechner/pi-ai").getModel
        >,
        tools: [],
        customTools: [],
        sessionManager: SessionManager.inMemory(),
        settingsManager,
        resourceLoader,
      });

      await session.prompt(prompt);

      const agentError = (session as unknown as { state: { error?: string } })
        .state?.error;
      if (agentError) {
        throw new Error(`Feedback extraction LLM error: ${agentError}`);
      }

      const raw = session.getLastAssistantText() ?? "";
      const durationSeconds = Math.round((Date.now() - start) / 1000);
      const messages =
        (session as unknown as { state: { messages?: unknown[] } }).state
          ?.messages ?? [];
      const usage = sumUsageFromSessionMessages(messages);
      result.llmMetrics = { ...usage, durationSeconds };

      candidates = parseFeedbackResponse(raw);
      result.extracted = candidates.length;
      logger.info(
        `Extracted ${candidates.length} candidate learning(s) from feedback`,
      );
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      result.errors.push(`Feedback extraction LLM call failed: ${msg}`);
      logger.warn(`Feedback extraction failed: ${msg}`);
      return result;
    }

    if (opts.dryRun) {
      logger.info("Dry run — skipping knowledge base writes");
      for (const candidate of candidates) {
        const gate = isHighSignalCandidate(candidate);
        if (gate.accepted) {
          result.saved++;
        } else {
          result.rejected++;
          logger.info(`Would reject: ${gate.reason}`);
        }
      }
      return result;
    }

    for (const candidate of candidates) {
      const gate = isHighSignalCandidate(candidate);
      if (!gate.accepted) {
        result.rejected++;
        logger.info(`Feedback candidate rejected: ${gate.reason}`);
        continue;
      }

      try {
        const saveResult = await saveKnowledgeBase(
          opts.config,
          opts.targetRepo,
          candidate,
        );
        if (saveResult.ok) {
          if (saveResult.status === "saved") result.saved++;
          else if (saveResult.status === "updated") result.updated++;
          result.learnings.push(candidate.learning);
        } else {
          result.rejected++;
          logger.info(`Feedback candidate save skipped: ${saveResult.reason}`);
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        result.errors.push(`Save failed for candidate: ${msg}`);
        logger.warn(`Feedback save error: ${msg}`);
      }
    }

    logger.info(
      `Feedback extraction complete: ${result.saved} saved, ${result.updated} updated, ${result.rejected} rejected`,
    );
    return result;
  } finally {
    for (const [key, value] of Object.entries(envSnapshot)) {
      if (value === undefined) delete process.env[key];
      else process.env[key] = value;
    }
  }
}
